name: LevelUpGameHub ShortURL Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: |
          composer install
          cp .env.production .env
          php artisan key:generate --ansi
          sudo apt-get install -y sshpass

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          sshpass -p 'LibrA21101998' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ levelupgame@153.92.5.213:/home/levelupgame/shrt.levelupgamehub.com/
          sshpass -p 'LibrA21101998' ssh -o StrictHostKeyChecking=no levelupgame@153.92.5.213 'cd /home/levelupgame/shrt.levelupgamehub.com && php artisan key:generate --ansi && php artisan migrate --force && php artisan optimize:clear && php artisan config:clear'
